/// Flutter icons ReadyToCook
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ReadyToCook
///      fonts:
///       - asset: fonts/ReadyToCook_1.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ReadyToCook {
  ReadyToCook._();

  static const _kFontFam = 'ReadyToCook';
  static const _kFontPkg = null;

  static const IconData baking = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
